#ifndef NETWORKSERVER_GLOBAL_H
#define NETWORKSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKSERVER_LIBRARY)
#  define NETWORKSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKSERVER_GLOBAL_H
